apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-sequestration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: equation-with-carbon
  template:
    metadata:
      labels:
        app: equation-with-carbon
    spec:
      containers:
      - name: equation-with-carbon
        image: equation-with-carbon:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: carbon-equation-service
spec:
  selector:
    app: equation-with-carbon
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30700